### ISSUE TITLE
eupi-camera EuPI 수신 구현

### ISSUE THREAD

**Issue by SeonJK** [euphony-io/wave-cam#10]
- [x] EuRxManager 인스턴스 생성
- [x] 주파수 수신 시 동작 연결

**Comment by SeonJK** [comment]
@designe @yeonns 
안녕하세요! 해당 이슈와 관련하여 문의 드립니다!

현재 eupi-camera는 두개의 주파수를 수신하려고 합니다. 이때 하나의 EuRxManager를 이용해서 두개의 주파수를 수신할 수 있는지 궁금합니다!

예를 들어
```kotlin
rxManager.setOnWaveKeyDown(18000) {
    // do something
}
rxManager.setOnWaveKeyDown(21000) {
    // do something
}
```

이렇게 구현했을 경우 아래의 setOnWaveKeyDown만 설정이 되는 것은 아닌지 궁금해서 문의 드립니다!!
주말에도 계속 수고해주셔서 정말 감사합니다..!! 이와 더불어 TxManager 싱글톤 관련 디스커션도 얼른 올리도록 하겠습니다!ㅠㅠ

**Comment by yeonns** [comment]
@SeonJK 주말에도 고생이 많으십니다 ㅎㅎ 
작성해주신 코드처럼 하나의 EuRxManager로 두 개의 주파수 수신은 가능합니다! 
euphony내의 `java-sample` 앱을 보면 각 주파수별로 setOnWaveKeyDown을 정의해서 쓰고 있으니 참고하시면 좋을 거 같아요 :smile: 
https://github.com/euphony-io/euphony/blob/master/java-sample/src/main/java/co/euphony/sample/fragments/rx/RxEuPIFragment.java

**Comment by SeonJK** [comment]
오 그렇군요!!! 정말 감사합니다ㅎㅎ 해당 앱 참고해보겠습니다😊
